JOBS-3491 Estimates API: api docs (internal & public)
Smartling/api-docs pull request #140
Opened 2021-04-30 11:46 UTC by aneprel-smartling

2021-04-30 13:15 UTC, andreyfurdylo requested changes

2021-04-30 13:15 UTC, andreyfurdylo commented on spec/openapi.yaml
> +        fuzzyProfileUid:
this is an internal parameter. Should be deleted.

2021-04-30 13:15 UTC, andreyfurdylo commented on spec/openapi.yaml
> +      properties:
`contentType` parameter is missing

2021-05-05 07:45 UTC, andreyfurdylo commented on spec/openapi.yaml
> +            - JOB_CONTENT_TRANSLATION
It is a wrong content type
They us `name`:
 - TRANSLATION
 - UNAUTHORIZED
 etc.

2021-05-05 07:48 UTC, andreyfurdylo approved these changes

2021-05-05 09:45 UTC, PavloMyrotiuk approved these changes

2021-05-05 09:45 UTC, merged