Delta 1551 update get async status/deleteContexts endpoints documentation
Smartling/api-docs pull request #163
Opened 2021-12-06 15:56 UTC by dsavchenko-sm

2021-12-07 11:08 UTC, vbarhatov requested changes
Discussed with Dmitry. There are some issues that have to be to fix

2021-12-07 11:20 UTC, dsavchenko-sm commented on spec/openapi.yaml
> +          Check the status of the async request and get the results once the request is completed
fixed

2021-12-07 12:29 UTC, dsavchenko-sm commented on spec/openapi.yaml
> +      deprecated: true
added

2021-12-07 16:48 UTC, vbarhatov requested changes
much better but a few things should be updated

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +      deprecated: true
`This endpoint is deprecated and will be deleted. We recommend to use <a>Retrieve asynchronous process results</a> endpoint`

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +      summary: Delete the contexts
"Delete contexts"

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +        Submits async operation to delete the contexts metadata and the content.
"Initiates an asynchronous process to delete the contexts."

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +          Check the status of the async process and get the results once the process is completed
> of the asynchronous process

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +                          message: Async process not found
> Asynchronous process

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +        - description: Identifier of the process obtained when running asynchronous request.
> Identifier of the asynchronous process obtained when the process was initiated.

2021-12-07 16:48 UTC, vbarhatov commented on spec/openapi.yaml
> +        Submits async operation to delete the contexts metadata and the content.
Please update "Delete the context" endpoint and change the first sentence in the description:
> Deletes the context.

2021-12-09 10:40 UTC, MihailTymoshenko approved these changes
👍

2021-12-09 10:52 UTC, closed without merging

2021-12-16 13:41 UTC, vbarhatov reviewed
ok