JOBSBATCH-110 Move Job Batches api to V2
Smartling/api-docs pull request #75
Opened 2019-07-26 00:30 UTC by dkBrazz

2019-07-29 17:25 UTC, dimitrystd commented
@hgronberg-smartling Please don't merge it even if it's reviewed. We would like to get feedback from 2 early adopters and then make an official public release.

2019-07-29 17:30 UTC, dimitrystd commented on spec/openapi.yaml
> +      2. Client Creates a new Batch for this Job with the declared list of
Maybe
```
Client creates a new Batch for this Job with a list of file URIs that will be uploaded into the Job
```

2019-07-29 17:34 UTC, dimitrystd commented on spec/openapi.yaml
> +      4. Client can cancel some of declared files if there is no reason
Maybe
```
If one of the declared files cannot be uploaded (for whatever reason) then such file upload can be canceled. An example, a file has no translatable content or there is some error with file generation. In this case, client can cancel file upload and unblock Batch execution
```

2019-07-29 17:35 UTC, dimitrystd commented on spec/openapi.yaml
> +      5. When all files are uploaded or canceled, "execute" is automatically
```
When all files from the declared list are uploaded or canceled...
```

2019-07-29 17:36 UTC, dimitrystd commented on spec/openapi.yaml
> +      6. Batch execution process waiting until all asynchronous processes with
```
Batch execution process waits ...
```

2019-07-29 17:40 UTC, dimitrystd commented on spec/openapi.yaml
> +          description: A list of File Uris to be uploaded later
Maybe `URIs`

2020-09-21 09:11 UTC, PavelLoparev approved these changes

2020-09-21 12:23 UTC, dimitrystd commented
@rachelsmartling Can you pls review and publish?

2020-09-22 17:38 UTC, rachelsmartling commented on spec/openapi.yaml
> +  - name: Job Batches V1
sdfghjk

2020-09-22 18:44 UTC, rachelsmartling requested changes

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      completed, adding file to a job is also asynchronous, and job can't be
```suggestion
      completed. Adding file to a job is also asynchronous, and job can't be
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      This forces third-party integration poll every file after every step.
```suggestion
      This forces a third-party integration poll for every file after every step.
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      after it accepted file from client it conducts this file through all steps
```suggestion
      after it accepts the file from the Smartling User, it processes this file through all steps
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      From the client side flow consists of simple steps:
```suggestion
      From the Smartling user's perspective, the flow consists of the following simple steps:
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      1. Client creates Job (or uses existing one, which isn't currently
```suggestion
      1. Create a Job (or uses existing one, which isn't currently
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      2. Client Creates a new Batch for this Job with the declared list of
```suggestion
      2. Create a new Batch for this Job with the declared list of
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      3. Client uploads files into the batch giving target locales list
```suggestion
      3. Upload the files into the batch giving target locales list
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      4. Client can cancel some of declared files if there is no reason
```suggestion
      4. You can cancel some of the declared files if there is no reason
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      6. Batch execution process waiting until all asynchronous processes with
```suggestion
      6. Batch execution process waits until all asynchronous processes
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      uploading and adding to the Job finished and then, if was requested, authorizes the Job.
```suggestion
      are complete and then, if requested, authorizes the Job for translation.
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      7. Clients can check batch status and see if all files uploaded and
```suggestion
      7. You can check batch status and see if all files have been uploaded and
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      attached successfully, what errors happened for each file, and statistics
```suggestion
      attached successfully. You can also see if any errors occurred for each file upload and the statistics
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      for added/skipped strings.
```suggestion
      for ingested/excluded strings.
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +                    it is uploaded. Authorization is happened only when a job is
```suggestion
                    it is uploaded. Authorization happens only when a job is
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +        File names can be added during files uploading to the batch, but only before the batch will start executing.
```suggestion
        File names can be added while files are uploading to the batch, but only before the batch will start executing.
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +        The batch is executed once the last file in the initial list or added files is uploaded or cancelled
```suggestion
        The batch is executed as soon as the last file in the initial list or added files are uploaded or cancelled
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +                    it is uploaded. Authorization is happened only when a job is
```suggestion
                    it is uploaded. Authorization happens only when a job is
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +      description: A smartling locale which file should be authorized to
```suggestion
      description: A smartling locale which the file should be authorized and translated into
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +            if set true then job will be authorized when upload and attach
```suggestion
            if the set is true then the job will be authorized when uploaded and attach
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +            if set true then job will be authorized when upload and attach
```suggestion
            if the set is true then the job will be authorized when uploaded and attach
```

2020-09-22 18:44 UTC, rachelsmartling commented on spec/openapi.yaml
> +          description: A list of File Uris to be uploaded later
```suggestion
          description: A list of File URI's to be uploaded later
```

2020-09-23 12:38 UTC, merged